# Generated by Django 5.0.6 on 2024-06-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('M', 'Music'), ('F', 'Food & Drink'), ('H', 'Hobbies'), ('T', 'Theater'), ('D', 'Dating')], default='M', max_length=1)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=200)),
                ('age_restriction', models.IntegerField()),
            ],
        ),
    ]
