# Generated by Django 5.0.6 on 2024-06-28 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_summary', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('M', 'Music'), ('F', 'Food & Drink'), ('H', 'Hobbies'), ('T', 'Theater'), ('D', 'Dating')], default='M', max_length=1)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=200)),
                ('age_restriction', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
