# Generated by Django 5.0.6 on 2024-06-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Default Event Name', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='short_summary',
            field=models.CharField(default='Default Summary', max_length=100),
        ),
    ]
